version: '3'

services:
    workspace:
        build: ./php
        volumes:
            - /mnt/hgfs/workspace:/var/www
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:172.18.0.1"
        ports:
           - "9050:9050"
        tty: true
### Nginx Server Container ##################################

#    nginx:
#        build:
#            context: ./nginx
#        volumes:
#            - ./logs/nginx/:/var/log/nginx
#            - ./nginx/sites/:/etc/nginx/sites-available
#        ports:
#            - "80:80"

